version: '3'
services:
  mongodb:
      image: mongo
      container_name: mongodb
      restart: unless-stopped
      command: mongod --auth
      ports:
        - "27017:27017"
      environment:
        MONGO_INITDB_ROOT_USERNAME: mensa-admin
        MONGO_INITDB_ROOT_PASSWORD: mensa!!123
        MONGO_INITDB_DATABASE: mensa
        MONGODB_DATA_DIR: /data/db
        MONDODB_LOG_DIR: /dev/null
      volumes:
        - mongodbdata:/data/db
volumes:
  mongodbdata:
    driver: local